### ISSUE TITLE
Startup Guide

### ISSUE THREAD

**Issue by rexdivakar** [Open-Dev-Community/Hacktoberfest#2]
### **This project is perfect for your first pull request**
**Instructions-**
Fork this Repository using the button at the top
Clone your forked repository to your pc
Create a new branch for your modifications (ie. git branch new-user and check it out git checkout new-user and git checkout -b new-user)
Add your profile image in image/
Add your files (git add -A), commit (git commit -m "added myself") and push (git push origin new-user)
Create a pull request
Star this repository

**Comment by DipanNama** [comment]
Can I do this PR when the competition starts (i.e after 1st october)?

**Comment by rexdivakar** [comment]
Sorry buddy this won't account as valuable PR for the Hacktoberfest, we added this for newbie's who didn't have expr raising PR @DipanNama

**Comment by DipanNama** [comment]
ok sir, Thank you
